{% set name = "brotlicffi" %}
{% set version = "1.1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b77827a689905143f87915310b93b273ab17888fd43ef350d4832c4a71083c13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - cffi >=1.0.0
  run:
    - cffi >=1.0.0
    - python

test:
  source_files:
    - test
  imports:
    - brotlicffi
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot invoke upstream tests because of missing 'testdata' directory in git/pypi sources
    # ImportError while loading conftest '/.../conda-bld/brotlicffi_1762941054066/test_tmp/test/conftest.py'.
    # E   FileNotFoundError: [Errno 2] No such file or directory: '...conda-bld/brotlicffi_1762941054066/test_tmp/libbrotli/tests/testdata'
    # - pytest -v test
  requires:
    - pip

about:
  home: https://github.com/python-hyper/brotlicffi
  summary: Python CFFI bindings to the Brotli library
  description: Python CFFI bindings to the Brotli library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-hyper/brotlicffi
  doc_url: https://github.com/python-hyper/brotlicffi/blob/main/README.rst

extra:
  recipe-maintainers:
    - sarthakpati
    - sethmlarson
    - katietz